name: Node.js CI

on:
  pull_request:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run build
    - name: Test
      run: npm test
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        NEXT_PUBLIC_BASE_PATH: /homepage_v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
